name: $(Date:yyyy.MM.dd).$(Rev:r)
jobs:
  - job:
    displayName: Generate and Publish Docs
    pool:
      vmImage: vs2017-win2016
    steps:
      - checkout: self
        persistCredentials: true
        
      - script: |
          git config --global user.email "build@xpike.org"
          git config --global user.name "Build Agent"
          git clone https://github.com/xpike/documentation.git
          git clone https://github.com/xpike/microsoft-extensions.git
          git clone https://github.com/xpike/ioc.git
          git clone https://github.com/xpike/configuration.git
          git clone https://github.com/xpike/settings.git
          dir 
        workingDirectory: $(Agent.TempDirectory) 

      - template: gen-docs.yml
        parameters:
          repoRoot: microsoft-extensions

      - template: gen-docs.yml
        parameters:
          repoRoot: ioc

      - template: gen-docs.yml
        parameters:
          repoRoot: configuration

      - template: gen-docs.yml
        parameters:
          repoRoot: settings

      - task: chrismason.vsts-docfxtasks.docfx-extension-build-task.DocFxTask@0
        displayName: 'Create Complete Documentation'
        inputs:
          solution: '$(Agent.TempDirectory)/documentation/docfx_project/docfx.json'

      - task: CopyFiles@2
        displayName: Copy docs
        inputs:
          SourceFolder: $(Agent.TempDirectory)/documentation/docfx_project/_site
          Contents: |
            **
          TargetFolder: $(System.DefaultWorkingDirectory)
          OverWrite: true

      - script: |
          git add *
          git commit -a -m "Updated docs version $(Build.BuildNumber)"
          git push origin HEAD:dev
        workingDirectory: $(System.DefaultWorkingDirectory)
                  